### PR TITLE
Fix uint32_t overflow during ArrayBuffer buffer allocation

### LINKED ISSUE #2: Assertion: byteindex + elementSize <= bytelength() in Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer(Escargot::ExecutionState&, unsigned int, bool) [with Type = float]
###### Escargot version:

```
Checked revision: 46dd776
Build command: make x64.interpreter.debug
```

###### OS:

```
Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
new Float32Array({ length: 0x40000001 });
```

###### Backtrace:

```
escargot: src/runtime/TypedArrayObject.h:108: Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer(Escargot::ExecutionState&, unsigned int, bool) [with Type = float]: Assertion `byteindex + elementSize <= bytelength()' failed.

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6466801 in __GI_abort () at abort.c:79
#2  0x00007ffff645639a in __assert_fail_base (fmt=0x7ffff65dd7d8 "%s%s%s:%u: %s%sAssertion `%s\' failed.\\n%n", assertion=assertion@entry=0x5555557b11c0 "byteindex + elementSize <= bytelength()", file=file@entry=0x5555557b0e60 "src/runtime/TypedArrayObject.h", line=line@entry=108, function=function@entry=0x5555557b1fa0 <Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer<float>(Escargot::ExecutionState&, unsigned int, bool)::__PRETTY_FUNCTION__> "Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer(Escargot::ExecutionState&, unsigned int, bool) [with Type = float]") at assert.c:92
#3  0x00007ffff6456412 in __GI___assert_fail (assertion=0x5555557b11c0 "byteindex + elementSize <= bytelength()", file=0x5555557b0e60 "src/runtime/TypedArrayObject.h", line=108, function=0x5555557b1fa0 <Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer<float>(Escargot::ExecutionState&, unsigned int, bool)::__PRETTY_FUNCTION__> "Escargot::Value Escargot::ArrayBufferView::getValueFromBuffer(Escargot::ExecutionState&, unsigned int, bool) [with Type = float]") at assert.c:101
#4  0x0000555555662596 in Escargot::ArrayBufferView::getValueFromBuffer<float> (this=0x7ffff45dfbb0, state=..., byteindex=4, isLittleEndian=true) at src/runtime/TypedArrayObject.h:108
#5  0x000055555565fae3 in Escargot::TypedArrayObject<Escargot::Float32Adaptor, 4>::getOwnProperty (this=0x7ffff45dfbb0, state=..., P=...) at src/runtime/TypedArrayObject.h:246
#6  0x000055555572939e in Escargot::Object::set (this=0x7ffff45dfbb0, state=..., propertyName=..., v=..., receiver=...) at src/runtime/Object.cpp:717
#7  0x00005555557297a0 in Escargot::Object::setThrowsException (this=0x7ffff45dfbb0, state=..., P=..., v=..., receiver=...) at src/runtime/Object.cpp:781
#8  0x000055555565df73 in Escargot::builtinTypedArrayConstructor<Escargot::Float32ArrayObject, 4> (state=..., thisValue=..., argc=1, argv=0x7fffffffd230, isNewExpression=true) at src/runtime/GlobalObjectBuiltinTypedArray.cpp:219
#9  0x00005555556bd6a6 in Escargot::FunctionObject::processCall (this=0x7ffff45c6490, state=..., receiverSrc=..., argc=@0x7fffffffd498: 1, argv=0x7fffffffd230, isNewExpression=true) at src/runtime/FunctionObject.cpp:314
#10 0x00005555556bd27e in Escargot::FunctionObject::newInstance (this=0x7ffff45c6490, state=..., argc=@0x7fffffffd498: 1, argv=0x7fffffffdb10) at src/runtime/FunctionObject.cpp:261
#11 0x000055555559a003 in Escargot::ByteCodeInterpreter::newOperation (state=..., callee=..., argc=1, argv=0x7fffffffdb10) at src/interpreter/ByteCodeInterpreter.cpp:1286
#12 0x0000555555597957 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff465e2b0, programCounter=93824998356792, registerFile=0x7fffffffdb00, initAddressFiller=0x7fffffffdb88) at src/interpreter/ByteCodeInterpreter.cpp:760
#13 0x00005555555b4bdf in Escargot::Script::execute (this=0x7ffff45dc610, state=..., isEvalMode=false, needNewEnv=false, isOnGlobal=true) at src/parser/Script.cpp:80
#14 0x00005555555b4d31 in Escargot::Script::<lambda()>::operator()(void) const (__closure=0x7fffffffde90) at src/parser/Script.cpp:93
#15 0x00005555555b5d94 in std::_Function_handler<Escargot::Value(), Escargot::Script::sandboxExecute(Escargot::ExecutionState&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:302
#16 0x00005555556d28be in std::function<Escargot::Value ()>::operator()() const (this=0x7fffffffde90) at /usr/include/c++/7/bits/std_function.h:706
#17 0x00005555556d1403 in Escargot::SandBox::run(std::function<Escargot::Value ()> const&) (this=0x7fffffffde00, scriptRunner=...) at src/runtime/SandBox.cpp:36
#18 0x00005555555b4e0e in Escargot::Script::sandboxExecute (this=0x7ffff45dc610, state=...) at src/parser/Script.cpp:94
#19 0x0000555555755185 in eval (context=0x7ffff4660d90, str=0x7ffff45dd250, fileName=0x7ffff45dd1b0, shouldPrintScriptResult=false) at src/shell/Shell.cpp:44
#20 0x0000555555755ad4 in main (argc=2, argv=0x7fffffffe1b8) at src/shell/Shell.cpp:127
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2.

Signed-off-by: Robert Fancsik <frobert@inf.u-szeged.hu>

### CODE REVIEW

File: src/runtime/GlobalObjectBuiltinTypedArray.cpp [hunk 1]
```diff
@@ -211,8 +211,13 @@ Value builtinTypedArrayConstructor(ExecutionState& state, Value thisValue, size_
             uint64_t length = inputObj->length(state);
             ASSERT(length >= 0);
             unsigned elementSize = obj->elementSize();
+            uint64_t buffer_size = length * elementSize;
```
Comment (ksh8281) [inline src/runtime/GlobalObjectBuiltinTypedArray.cpp]: I am sorry to bother you.
Could you change buffer_size to bufferSize?
Every otherthings are great

Comment (rerobika) [reply src/runtime/GlobalObjectBuiltinTypedArray.cpp]: Of course! I didn't realize that, I've got used to the underscore naming convention! :)
